### ISSUE TITLE
Location of "Concept" and "Motion Level" Annotations

### ISSUE THREAD

**Issue by llyx97** [facebookresearch/MovieGenBench#3]
Hi, thanks for sharing the great work! I am currently exploring the Movie Gen Video Bench and I'm having some difficulty locating the annotations for "Concept" and "Motion Level." Could you please provide guidance on where to find these specific annotations?

**Comment by luoyaqiao** [comment]
Working on it, will release soon.

**Comment by luoyaqiao** [comment]
Resolved and tags are released under benchmark/MovieGenVideoBenchWithTag.csv
