### ISSUE TITLE
The download link for Audio Bench seems broken

### ISSUE THREAD

**Issue by HUIZ-A** [facebookresearch/MovieGenBench#5]
Thank you, your work is very significant. 

The download link for Audio Benchmark appears to be broken. When I click on it, the following content is displayed: 

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access denied</Message>
</Error>

I'm wondering if this is an issue with my own network, or if the link is actually down?

**Comment by wnhsu** [comment]
Hi @HUIZ-A thank you for letting us know and the link is currently down. We are fixing it and will close this issue once fixed.

**Comment by wnhsu** [comment]
@HUIZ-A we have updated the path and confirmed it's working. Please check again thanks

**Comment by HUIZ-A** [comment]
cool!! thanks
